[build]
  publish = "dist" # This is the folder where your app is built
  prerender = false # Disable deprecated legacy prerendering

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
