[build]
  publish = "dist" # This is the folder where your app is built
  command = "yarn build" # Build command to create the production version of your site

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
