// src/pages/2companyPage/companyInfoData.js

const companyInfoData = [
    {
      title: "Company Information",
      paragraphs: [
        "Raijin Tech Hub is a leading IT solutions provider based in Kampala, Uganda, specializing in custom software development, IT consultancy, and digital transformation services. Established in 2024, we have quickly become a trusted technology partner for businesses across Uganda and East Africa.",
        "Our company is registered and licensed to operate in Uganda, maintaining full compliance with all local and international business regulations. We adhere to industry best practices and maintain professional certifications in software development and IT service delivery.",
        "Office Location: Kampala, Uganda | Business Hours: Monday - Friday, 8:00 AM - 6:00 PM EAT | Phone: +256 777 982 066 | Email: raijintechug@gmail.com",
        "We maintain strong partnerships with leading technology providers and continuously invest in the professional development of our team. Our commitment to quality, innovation, and customer satisfaction has enabled us to successfully deliver over 30 projects across 8 different industries in our first year of operation.",
        "Raijin Tech Hub is committed to contributing to Uganda's digital transformation agenda. We actively participate in technology communities, support local tech talent development, and work towards building a robust digital economy in East Africa.",
        "For detailed information about our services, past projects, and how we can help transform your business, please visit our website or contact our team directly. We offer free consultations to assess your technology needs and propose customized solutions.",
      ],
    },
    {
      title: "User Agreement",
      paragraphs: [
        "Welcome to Raijin Tech Hub. By accessing or using our website, services, or products, you agree to be bound by these terms and conditions. These terms constitute a legally binding agreement between you and Raijin Tech Hub, a registered IT services company operating in Uganda.",
        "Raijin Tech Hub provides a comprehensive range of IT services, including custom software development, web and mobile application development, IT consultancy, AI chatbot integration & automation, UI/UX design, cybersecurity services, and technical support. You agree to use our services only for lawful purposes and in accordance with all applicable laws and regulations of the Republic of Uganda.",
        "You are responsible for maintaining the confidentiality of any account information, passwords, and access credentials associated with your use of our services. Any activities that occur under your account are your responsibility. Please notify us immediately of any unauthorized use of your account.",
        "All content, trademarks, logos, software code, designs, and intellectual property on our website and in our services are owned by or licensed to Raijin Tech Hub. You may not reproduce, distribute, modify, or create derivative works from our content without our prior written consent, except as permitted for personal, non-commercial use.",
        "For paid services, you agree to pay all applicable fees as described in our pricing schedules, quotations, or service agreements. Payment terms and conditions will be clearly specified in individual contracts or invoices. Late payments may incur additional charges as specified in your service agreement.",
        "Raijin Tech Hub shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of our services, including but not limited to loss of profits, data loss, or business interruption. Our total liability is limited to the amount paid for the specific service in question.",
        "We reserve the right to terminate or suspend your access to our services at any time for violations of this agreement, non-payment, illegal activities, or for any other reason deemed necessary. You may terminate your use of our services by providing us with written notice as specified in your service agreement.",
        "This agreement shall be governed by and construed in accordance with the laws of the Republic of Uganda. Any disputes arising from this agreement shall be subject to the exclusive jurisdiction of the courts of Uganda. Raijin Tech Hub reserves the right to modify or update this User Agreement at any time. We will provide reasonable notice of significant changes. Your continued use of our services after any changes constitutes acceptance of the new terms.",
      ],
    },
    {
      title: "Privacy Policy",
      paragraphs: [
        "Raijin Tech Hub is committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your data in compliance with Ugandan Data Protection laws and international standards including GDPR principles. For our complete Privacy Policy, please visit our dedicated Privacy Policy page.",
        "We collect personal information such as your name, email address, phone number, company name, and business details when you contact us, request services, or use our website. We also collect technical information such as IP addresses, browser type, device information, and website usage data to improve our services and user experience.",
        "We use your information to provide and improve our IT services, communicate with you about projects and updates, process service requests and transactions, provide customer support, and send relevant information about our services (with your consent). We may also use aggregated data for analytics and business intelligence purposes.",
        "Raijin Tech Hub implements industry-standard security measures to protect your data from unauthorized access, use, or disclosure. These include SSL/TLS encryption for data transmission, secure storage protocols, access controls, regular security audits, and staff training on data protection. However, no method of transmission over the internet is 100% secure.",
        "We may share your information with trusted third-party service providers (hosting, email services, analytics) who assist in our operations and are bound by confidentiality agreements. We may also disclose information when required by law, court order, or government regulations in Uganda or applicable jurisdictions. We will never sell your personal information to third parties.",
        "You have the right to access, correct, or delete your personal information. You may also request data portability, object to processing, or withdraw consent at any time. To exercise these rights, please contact us at raijintechug@gmail.com. We will respond to your request within 30 days in accordance with applicable data protection laws.",
        "Our website uses cookies and similar tracking technologies to enhance your browsing experience, analyze website traffic, and improve our services. You can control cookies through your browser settings. Disabling cookies may affect certain website functionality. We use essential, analytics, and preference cookies as detailed in our full Privacy Policy.",
        "We retain your personal information only for as long as necessary to fulfill the purposes outlined in this policy, comply with legal obligations, resolve disputes, and enforce our agreements. When data is no longer required, we securely delete or anonymize it in accordance with our data retention policies and legal requirements.",
        "Raijin Tech Hub may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. We will notify you of any material changes by posting the new Privacy Policy on our website and updating the 'Last Updated' date. Your continued use of our services after any changes constitutes acceptance of the updated policy.",
      ],
    },
    {
      title: "Terms of Service",
      paragraphs: [
        "These Terms of Service govern the provision and use of all Raijin Tech Hub IT services and solutions. For our complete Terms of Service with detailed legal provisions, please visit our dedicated Terms of Service page. By engaging our services, you acknowledge that you have read, understood, and agree to be bound by these terms.",
        "Raijin Tech Hub offers a comprehensive range of IT services including: Custom Software Development (web and mobile applications, enterprise systems), IT Consultancy and Strategy, AI Integration & Chatbot Solutions (intelligent automation, conversational AI), UI/UX Design and Development, Cybersecurity and Penetration Testing, Digital Transformation and Automation, Technical Support and Maintenance, and Training and Capacity Building. The specific scope, deliverables, timelines, and pricing for each service will be detailed in individual agreements, proposals, or statements of work (SOW).",
        "Clients are expected to provide accurate, complete, and timely information required for service delivery, including access to necessary systems, data, and resources. Clients are responsible for their use of delivered services and must ensure compliance with all applicable laws and regulations. Timely feedback and approvals are essential for project success.",
        "Raijin Tech Hub commits to delivering services in a professional manner consistent with industry standards. We will make reasonable efforts to meet agreed timelines and specifications. However, delays may occur due to unforeseen circumstances, client-side delays, scope changes, or force majeure events. We will communicate any such delays promptly and work to minimize their impact.",
        "For software development projects, clients will have opportunities to review and accept deliverables at defined milestones. We provide warranty periods (typically 30-90 days post-delivery) for bug fixes and corrections at no additional cost, as specified in individual project agreements. Warranties do not cover issues arising from client modifications, third-party integrations, or misuse.",
        "Upon full payment, clients own all custom code, designs, and documentation created specifically for their project. We grant clients a perpetual, worldwide, non-exclusive license to use the deliverables. Raijin Tech Hub retains ownership of proprietary tools, frameworks, methodologies, and pre-existing code libraries used in projects. Third-party components are subject to their respective licenses. All intellectual property transfers are documented in writing.",
        "Both Raijin Tech Hub and clients agree to maintain strict confidentiality of proprietary and sensitive information shared during engagements. This includes business strategies, technical data, source code, user information, and any information marked as confidential. Exceptions include information that is publicly available, independently developed, or lawfully obtained from third parties. We process personal data in accordance with our Privacy Policy and applicable data protection laws.",
        "Payment terms are typically structured as: 30% deposit upfront, 40% at project midpoint, and 30% upon completion. Invoices are due within 14 days of issuance. Late payments may incur a 5% monthly interest charge. Deposits are non-refundable once work has commenced. Third-party costs (hosting, licenses, services) are billed separately and require client approval.",
        "Either party may terminate a service agreement with 30 days written notice. Immediate termination is permitted for material breach, non-payment, illegal activities, or circumstances beyond reasonable control. Upon termination, clients must pay for all work completed to date and retain licenses for delivered components per agreed terms. Specific termination clauses and refund policies will be outlined in individual contracts.",
        "These Terms are governed by the laws of the Republic of Uganda. Disputes will first be addressed through good faith negotiations. If unresolved within 30 days, disputes shall be submitted to mediation in Kampala, Uganda. If mediation fails, disputes are subject to the exclusive jurisdiction of Ugandan courts. For complete legal terms, warranties, limitations of liability, and dispute resolution procedures, please review our full Terms of Service document.",
      ],
    },
    {
      title: "Disclaimer",
      paragraphs: [
        "This Disclaimer limits Raijin Tech Hub's legal liability and clarifies important aspects of our services. Please read this carefully in conjunction with our complete Terms of Service and Privacy Policy.",
        "The information provided by Raijin Tech Hub on our website, in our marketing materials, and through our communications is for general informational purposes only. While we strive to provide accurate, current, and complete information, we make no warranties or representations about its completeness, accuracy, reliability, suitability, or availability. Any reliance you place on such information is strictly at your own risk.",
        "While Raijin Tech Hub is committed to delivering high-quality IT services and solutions using industry best practices, we cannot guarantee specific business outcomes, results, or performance metrics. The success of IT solutions depends on various factors including but not limited to: user adoption, data quality, existing infrastructure, business processes, market conditions, and proper system maintenance. Results may vary based on individual circumstances.",
        "Our website may contain links to third-party websites, services, tools, or resources. These links are provided for convenience and informational purposes only. Raijin Tech Hub is not responsible for the content, accuracy, availability, privacy practices, or security of these third-party websites. The inclusion of any link does not imply endorsement, and you access third-party sites at your own risk.",
        "To the fullest extent permitted by law, Raijin Tech Hub disclaims all liability for any damages, losses, or issues arising out of or in connection with the use of our services, website, or information. This includes but is not limited to: direct, indirect, incidental, consequential, special, exemplary, or punitive damages; loss of profits, revenue, data, or business opportunities; system downtime or security breaches; and any other economic losses.",
        "Services are provided 'as is' and 'as available' without warranties of any kind, either express or implied, except as expressly stated in individual service agreements. We disclaim implied warranties of merchantability, fitness for a particular purpose, and non-infringement to the extent permitted by law. We do not warrant that our services will be uninterrupted, error-free, or completely secure.",
        "The information provided by Raijin Tech Hub does not constitute professional legal, financial, or business advice. It should not be relied upon as such. For advice tailored to your specific situation, circumstances, or legal requirements, please consult with qualified professionals in the relevant fields. Technology recommendations are based on current industry standards and may need adjustment for specific use cases.",
        "Raijin Tech Hub may modify, update, or discontinue this Disclaimer at any time without prior notice. Changes will be effective immediately upon posting on our website. Your continued use of our services after modifications constitutes acceptance of the updated Disclaimer. It is your responsibility to review this Disclaimer periodically for changes.",
      ],
    },
  ];
  
  export default companyInfoData;